name: elera
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.7.0
  flutter_bloc: ^8.1.2
  intl: ^0.17.0
  cloud_firestore: ^4.5.3
  flutter_svg: ^2.0.5
  firebase_auth: ^4.2.2
  equatable: ^2.0.5
  firebase_core: ^2.10.0
  formz: ^0.6.0
  shared_preferences: ^2.1.0
  google_sign_in: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.19
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: MyIcons
      fonts:
        - asset: assets/fonts/MyIcons.ttf
